service: lambda-api-property
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1

functions:
  api:
    handler: handler.handle
    events:
      - httpApi: '*'
 
plugins:
  - serverless-offline
